<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- displays site properly based on user's device -->
    <title>Tom's Tasks | Home</title>

</head>
<body>

    <main>
        <h1>Create new to-do</h1>
        <form method="post" action="">
            <label for="content">What do you need to do?</label>
            <input type="text" name="content" id="content">
            <button type="submit">Add</button>
        </form>
    </main>

</body>
</html>