<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- displays site properly based on user's device -->
    <title>Tom's Tasks | Form Submission</title>

</head>
<body>

<main>
    <pre> <?php echo print_r($data, true) ?> </pre>
    <h1>Tom's Tasks</h1>
    <h2>Task submission status</h2>
    <?php
        if ($data['addResultStatus']) {
        echo '<p>To do successfully added!</p>';
    } else {
            echo '<p>Error! To do failed to be added.</p>';
        }
        ?>
    <a href="/"><button type="button">Return to home</button></a>
</main>

</body>
</html>