<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- displays site properly based on user's device -->
    <title>Tom's Tasks | Home</title>

</head>
<body>

    <main>
        <h1>Tom's Tasks</h1>
        <h2>Task list:</h2>
            <?php echo \App\ViewHelpers\ViewTasksViewHelper::displayTasks($tasks); ?>
    </main>

</body>
</html>